routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home/login', function () {
    return view('auth/login');
});

Route::get('/home/delete', function () {
    return view('auth.delete');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home/event', 'EventsController@create')->name('event');

Route::get('/home/viewEvents', 'EventsController@viewEvents')->name('viewEvents');

Route::get('/home/events/{id}', 'EventsController@drop')->name('drop');

Route::get('/home/communication/{id}', 'CommunicationsController@show')->name('show');

Route::get('/home/communicaton/{id}', 'CommunicationsController@create')->name('create');

Route::get('/home/usersinfo/{id}', 'UsersController@info')->name('userinfo');

Route::post('/home/createEvent', 'EventsController@store')->name('evt');

Route::get('/home/users', 'UsersController@index')->name('users');

Route::post('/home/users', 'UsersController@sendPush')->name('send-push');

Route::resource('communications', 'CommunicationsController');

Route::post('/dlt', 'EventsController@dlt')->name('dlt')->middleware('delete');

Route::get('/home/com/{id}', 'CommunicationsController@dlt')->name('dlts');

// Route::get('/delt', 'EventsController@dlt');

// Route::get('/communications/create/{value}', 'CommunicationsController@create')->name('creat');

// Route::get('/password/reset', 'HomeController@index')->name('home');

// Route::get('/users', function () {
//     return 'Hello   ';
// });

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $table = "events";

    protected $fillable = [
        'name','description',
    ];
}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Illuminate\Support\Facades\DB;
use App\Communication;
use Illuminate\Http\Request;

class EventsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function create()
    {

        return view('home.event.create');
    }


    public function store(Request $request,Event $event)
    {
        $event->name = $request->name;
        $event->description = $request->description;
        $event->save();
        $arr['events'] = DB::table('events')->paginate(10);
        return view('home.event.index')->with($arr);
    }

    public function drop($id)
    {
        $event = Event::find($id);
        $com = Communication::all();
        foreach($com as $c){
            
            if($c->eventId == $event->id)
            {
                // dd($c->eventId == $event->id);
                Communication::destroy($c->id);
            }
        }
        Event::destroy($id);
        $arr['events'] = DB::table('events')->paginate(10);
        return view('home.event.index')->with($arr);
    }


    public function dlt(Request $request)
    {
        echo $request;
        // $arr['users'] = User::find($id);
        // return view('home.users.info')->with($arr);
    }

    public function viewEvents()
    {   
        
        $arr['events'] = DB::table('events')->paginate(10);
        return view('home.event.index')->with($arr);
        
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/home/events/create.blade.php
@extends('layouts.admin')

@section('content')


<?php
$id=0;
?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Add Communications</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item "><a href="{{ route('home') }}">Dashboard</a></li>
              <li class="breadcrumb-item "><a href="{{ route('communications.index')}}">Events</a></li>
              <li class="breadcrumb-item"><a href="{{ route('users') }}">Users</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<section class="content">
    <div class="container-fluid">
     <form method="post" action="{{route('communications.store')}}">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <!-- <div class="form-group">
            <div class="row">
                <label class="col-md-3">Titlt</label>
                <div class="col-md-6"><input type="text" name="title" class="form-control"></div>
                <div class="clearfix"></div>
            </div>
        </div>  -->

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Communication Name</label>
                <div class="col-md-6"><input type="text" name="name" class="form-control" required></div>
                <div class="clearfix"></div>
            </div>
        </div> 

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Event Name</label>
                <div class="col-md-6"><input type="text" name="event_name" class="form-control" value="{{$event->name}}" readonly required></div>
                <div class="clearfix"></div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">After What Time Interval</label>
                <div class="col-md-3"><input type="number" name="occurance" class="form-control" placeholder="" required></div>
                <div class="col-md-3">
                    <select id="occuranceUnit" name="occuranceUnit" class="form-control">
                    <option value="minutes">Minutes</option>
                    <option value="hours">Hours</option>
                    <option value="days">Days</option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>


        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Overrideable</label>
                <input checked class="col-md-1" type="checkbox" id="overrideable" name="overrideable" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="row">
            <label class="col-md-3">Mode of Notification</label>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Email</label>
                <input id="email" checked class="col-md-1" type="checkbox" id="email" name="email" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>
        <div id="emailInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Subject</label>
                <div class="col-md-6"><input type="text" name="emailSubject" class="form-control" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Body</label>
                <div class="col-md-6"><textarea class="form-control" name="emailBody"></textarea></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Firebase Notification</label>
                <input checked class="col-md-1" type="checkbox" id="firebase" name="firebase" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="firebaseInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Subject</label>
                <div class="col-md-6"><input type="text" name="firebaseSubject" class="form-control" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Body</label>
                <div class="col-md-6"><textarea class="form-control" name="firebaseBody"></textarea></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-2">SMS</label>
                <input checked class="col-md-1" type="checkbox" id="sms" name="sms" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="smsInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">SMS Content</label>
                <div class="col-md-6"><input type="text" name="smsContent" class="form-control" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Whats App</label>
                <input checked class="col-md-1" type="checkbox" id="whatsapp" name="whatsapp" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="whatsappInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Whats App Content</label>
                <div class="col-md-6"><input type="text" name="whatsappContent" class="form-control" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-info" value="Save">
        </div>
    </form>
    </div>
</section>

@endsection

resources/views/home/events/edit.blade.php
@extends('layouts.admin')

@section('content')



<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Edit/ View Communications</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item "><a href="{{ route('home') }}">Dashboard</a></li>
              <li class="breadcrumb-item "><a href="{{ route('communications.index') }}">Events</a></li>
              <li class="breadcrumb-item"><a href="{{ route('users') }}">Users</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<section class="content">
    <div class="container-fluid">
     <form method="post" action="{{route('communications.update',$com->id)}}">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="put">
        <!-- <div class="form-group">
            <div class="row">
                <label class="col-md-3">Titlt</label>
                <div class="col-md-6"><input type="text" name="title" class="form-control"></div>
                <div class="clearfix"></div>
            </div>
        </div>  -->
<!-- 
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Communication Name</label>
                <div class="col-md-6"><input type="text" name="name" class="form-control" required value="{{$com->name}}"></div>
                <div class="clearfix"></div>
            </div>
        </div>  -->

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Communication Name</label>
                <div class="col-md-6"><input type="text" name="name" class="form-control" required value="{{$com->name}}"></div>
                <div class="clearfix"></div>
            </div>
        </div> 

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Event Name</label>
                <?php
                use App\Event;
                $event = Event::find($com->eventId);
                ?>
                <div class="col-md-6"><input type="text" name="eventName" class="form-control" value="{{$event->name}}" readonly required></div>
                <div class="clearfix"></div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">After What Time Interval</label>
                <?php
                if($com->occuranceUnit=="days")
                {
                    $com->occurance = $com->occurance/(24*60);
                }
                elseif($com->occuranceUnit=="hours"){
                    $com->occurance = $com->occurance/60;
                }
                ?>
                <div class="col-md-3"><input type="number" name="occurance" class="form-control" placeholder="" value="{{$com->occurance}}" required></div>
                <div class="col-md-3">
                    <select id="occuranceUnit" name="occuranceUnit" class="form-control">
                    @if ($com->occuranceUnit=="days")
                    <option value="minutes">Minutes</option>
                    <option value="hours">Hours</option>
                    <option value="days" selected>Days</option>
                    @elseif ($com->occuranceUnit=="hours")
                    <option value="minutes">Minutes</option>
                    <option value="hours" selected>Hours</option>
                    <option value="days">Days</option>
                    @else
                    <option value="minutes" selected>Minutes</option>
                    <option value="hours">Hours</option>
                    <option value="days">Days</option>
                    @endif
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Overrideable</label>
                @if ($com->overrideable==1)
                <input checked class="col-md-1" type="checkbox" id="overrideable" name="overrideable" value="1" class="form-control">
                @else
                <input class="col-md-1" type="checkbox" id="overrideable" name="overrideable" value="1" class="form-control">
                @endif
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
            <label class="col-md-3">Mode of Notification</label>
            </div>
        </div>
        @if ($com->email==1)
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Email</label>
                <input id="email" checked class="col-md-1" type="checkbox" id="email" name="email" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>
        <div id="emailInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Subject</label>
                <div class="col-md-6"><input type="text" name="emailSubject" class="form-control"value="{{$com->emailSubject}}" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Body</label>
                <div class="col-md-6">
                <!-- <input type="text" name="emailBody" class="form-control" value="{{$com->emailBody}}" placeholder="" > -->
                <textarea class="form-control" name="emailBody"><?php echo $com->emailBody; ?></textarea>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @else
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Email</label>
                <input id="email" class="col-md-1" type="checkbox" id="email" name="email" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>
        <div id="emailInfo" style="display:none;">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Subject</label>
                <div class="col-md-6"><input type="text" name="emailSubject" class="form-control" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Email Body</label>
                <div class="col-md-6"><textarea class="form-control" name="emailBody"></textarea></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @endif
        
        @if ($com->firebase==1)
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Firebase Notification</label>
                <input checked class="col-md-1" type="checkbox" id="firebase" name="firebase" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="firebaseInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Subject</label>
                <div class="col-md-6"><input type="text" name="firebaseSubject" class="form-control" value="{{$com->firebaseSubject}}" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Body</label>
                <div class="col-md-6">
                <textarea class="form-control" name="firebaseBody"><?php echo $com->firebaseBody; ?></textarea>
                <!-- <input type="text" name="firebaseBody" class="form-control" placeholder="" value="{{$com->firebaseBody}}"> -->
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @else
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Firebase Notification</label>
                <input class="col-md-1" type="checkbox" id="firebase" name="firebase" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="firebaseInfo" style="display:none;">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Subject</label>
                <div class="col-md-6"><input type="text" name="firebaseSubject" class="form-control" placeholder="" ></div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Firebase Body</label>
                <div class="col-md-6"><textarea class="form-control" name="firebaseBody"></textarea></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @endif

        @if ($com->sms==1)
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">SMS</label>
                <input checked class="col-md-1" type="checkbox" id="sms" name="sms" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="smsInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">SMS Content</label>
                <div class="col-md-6"><input type="text" name="smsContent" class="form-control" value="{{$com->smsContent}}" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @else
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">SMS</label>
                <input class="col-md-1" type="checkbox" id="sms" name="sms" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="smsInfo" style="display:none;">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">SMS Content</label>
                <div class="col-md-6"><input type="text" name="smsContent" class="form-control" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @endif

        @if ($com->whatsapp==1)
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Whats App</label>
                <input checked class="col-md-1" type="checkbox" id="whatsapp" name="whatsapp" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="whatsappInfo">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Whats App Content</label>
                <div class="col-md-6"><input type="text" name="whatsappContent" class="form-control" value="{{$com->whatsappContent}}" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @else
        <div class="form-group">
            <div class="row">
                <label class="col-md-2">Whats App</label>
                <input class="col-md-1" type="checkbox" id="whatsapp" name="whatsapp" value="1" class="form-control">
                <div class="clearfix"></div>
            </div>
        </div>

        <div id="whatsappInfo" style="display:none;">
        <div class="form-group">
            <div class="row">
                <label class="col-md-3">Whats App Content</label>
                <div class="col-md-6"><input type="text" name="whatsappContent" class="form-control" placeholder=""></div>
                <div class="clearfix"></div>
            </div>
        </div>
        </div>
        @endif

        <div class="form-group">
            <input type="submit" class="btn btn-info" value="Save">
        </div>
    </form>
    </div>
</section>

@endsection

resources/views/home/events/index.blade.php
@extends('layouts.admin')

@section('content')



<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Events</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item "><a href="{{ route('home') }}">Dashboard</a></li>
              <li class="breadcrumb-item "><a href="{{ route('communications.index') }}">Events</a></li>
              <li class="breadcrumb-item active"><a href="{{ route('users') }}">Users</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->



<section class="content">
    <div class="container-fluid">
        <table class="table table-striped">
          <?php
          use Illuminate\Support\Facades\DB;
          $com = DB::table('communications')->where('eventId',$event->id)->paginate(10);
          ?>
            <tr>
                <th><a href="{{ route('create',$event->id)}}" class="btn btn-primary">Add Communication</a></th>
                <th></th>
                
            </tr>
              <tr>
                <th>{{ $event->name }} Event</th>
                <th><a href="{{ route('drop',$event->id)}}" class="btn btn-danger">Delete this Event</a></th>
              </tr>
              @foreach($com as $c)
                <tr>
                    <td>{{ $c->name }}</td>
                    <td> 

                    <a href="{{route('communications.edit',$c->id)}}" class="btn btn-info">Edit/ View</a>

                    <a href="{{route('dlts',$c->id)}}" class="btn btn-danger"  >Delete</a>
                    <!-- <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger"  >Delete</a>
                    <form action="{{route('communications.destroy',$c->id)}}" method="post">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"> -->
                    </form>

                    </td>
                </tr>

                @endforeach
        </table>
        {{$com->links()}}
    </div>
</section>


@endsection